// Generated by CoffeeScript 1.8.0
'use strict';
module.exports = function(grunt) {
  var pkg;
  require('load-grunt-tasks')(grunt);
  require('time-grunt')(grunt);
  pkg = grunt.file.readJSON('package.json');
  grunt.initConfig({
    clean: {
      dist: {
        files: 'dist/'
      }
    },
    less: {
      dist: {
        files: {
          'dist/style.css': ['less/main.less']
        },
        options: {
          sourceMap: true,
          sourceMapFilename: 'dist/style.css.map'
        }
      }
    }
  });
  grunt.registerTask('build', ['clean', 'less']);
  return grunt.registerTask('default', ['build']);
};
